/**
 * Bake the icons we actually use into `client/icons.js`.
 *
 * The full game-icons set is 4134 icons and several megabytes; shipping the
 * JSON to the browser to use twenty of them would be absurd, and pulling them
 * from a CDN breaks the moment the game is played over a tunnel or offline.
 * So this lifts exactly the ones named below into a plain string map at build
 * time, and the generated file is committed.
 *
 *   npm run icons
 *
 * game-icons.net is CC BY 3.0 — see ATTRIBUTION at the bottom of the output.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * name in the game → `set:icon`.
 *
 * game-icons for anything that is a thing in the world, remix-icon for plain
 * interface chrome. Keeping that split means the world never looks like a
 * settings screen and the settings screen never looks like a dungeon crawler.
 */
const WANTED = {
  // rail
  build: 'game-icons:claw-hammer',
  seeds: 'game-icons:plant-seed',
  supplier: 'game-icons:shopping-cart',
  upgrades: 'game-icons:upgrade',
  report: 'game-icons:chart',
  staff: 'game-icons:person',
  help: 'game-icons:help',

  // one per role, so a shift roster reads at a glance
  clerk: 'game-icons:cash',
  stocker: 'game-icons:cardboard-box',
  farmhand: 'game-icons:farmer',
  chef: 'game-icons:chef-toque',

  // fixtures
  shelf: 'game-icons:bookshelf',
  freezer: 'game-icons:fridge',
  checkout: 'game-icons:cash',
  plot: 'game-icons:field',
  station: 'game-icons:factory',
  crate: 'game-icons:cardboard-box',
  floor: 'game-icons:stone-path',

  // what you can do to a fixture
  tierup: 'game-icons:progression',
  move: 'game-icons:grab',
  rotate: 'game-icons:clockwise-rotation',
  empty: 'game-icons:broom',
  remove: 'game-icons:trash-can',
  label: 'game-icons:price-tag',

  // tab headings — one per group inside a menu that got too long to scroll
  walk: 'game-icons:walk',
  camera: 'game-icons:video-camera',
  menus: 'game-icons:hamburger-menu',
  today: 'game-icons:calendar',
  trouble: 'game-icons:hazard-sign',
  shop: 'game-icons:shop',
  fresh: 'game-icons:fruit-bowl',
  ambient: 'game-icons:mason-jar',
  cold: 'game-icons:snowflake-2',
  fixtures: 'game-icons:cog',

  // interface chrome
  search: 'ri:search-line',
  close: 'ri:close-line',
};

const sets = {};
const load = (set) => {
  if (!sets[set]) {
    sets[set] = JSON.parse(readFileSync(join(root, 'node_modules', `@iconify-json/${set}`, 'icons.json'), 'utf8'));
  }
  return sets[set];
};

const missing = [];
const out = {};

for (const [key, ref] of Object.entries(WANTED)) {
  const [setName, iconName] = ref.split(':');
  const set = load(setName);
  const icon = set.icons[iconName];
  if (!icon) { missing.push(ref); continue; }
  const w = icon.width ?? set.width ?? 24;
  const h = icon.height ?? set.height ?? 24;
  // width/height in em so every existing font-size rule keeps sizing them, and
  // currentColor so they inherit whatever the button is already coloured.
  out[key] = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" `
    + `width="1em" height="1em" fill="currentColor" aria-hidden="true">${icon.body}</svg>`;
}

if (missing.length) {
  console.error(`[icons] no such icon: ${missing.join(', ')}`);
  process.exit(1);
}

const body = Object.entries(out)
  .map(([k, v]) => `  ${k}: '${v.replace(/'/g, "\\'")}',`)
  .join('\n');

writeFileSync(join(root, 'client', 'icons.js'), `/**
 * GENERATED by \`npm run icons\` — do not edit.
 *
 * Add a name to WANTED in scripts/build-icons.js and re-run instead.
 *
 * Icons from game-icons.net (CC BY 3.0) and Remix Icon (Apache 2.0).
 */

const SET = {
${body}
};

/**
 * Asking for an icon that was never baked in used to interpolate the string
 * "undefined" into the markup and sit there looking like a rendering bug. It is
 * a missing build step, so it says so, at the first render rather than never.
 */
/**
 * For names that legitimately may not exist — an icon per authored worker kind,
 * say, where the kinds come from the database and the icons do not.
 *
 * \`ICONS[x] ?? fallback\` cannot do this: the strict lookup below throws before
 * \`??\` ever sees a value. Asking whether an icon exists is a different question
 * from asking for one, so it gets a different call.
 */
export const icon = (name, fallback = null) => (name in SET ? SET[name] : fallback);

export const ICONS = new Proxy(SET, {
  get(all, name) {
    if (typeof name !== 'string' || name in all) return all[name];
    // Bundlers and \`await import()\` probe objects for these.
    if (name === 'then' || name === '__esModule') return undefined;
    throw new Error(\`[icons] no icon "\${name}" — add it to WANTED in scripts/build-icons.js and run npm run icons\`);
  },
});
`);

console.log(`[icons] wrote client/icons.js — ${Object.keys(out).length} icons`);
